var GAME_LEVELS = [
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "               x f x              ",
   "               x   x              ",
   "               x   x              ",
   "               x   x              ",
   "               x   x              ",
   "               x   x              ",
   "              x     x             ",
   "             x       x            ",
   "                                  ",
   "                                  ",
   "                                  ",
   "                                  ",
   "                                  ",
   "                                  ",
   "                yy    m           ",
   "                yy                ",
   "                yy                ",
   "           xxxx                   ",
   "           x  x                   ",
   "             xx                   ",
   "     xxxxxxxxx                    ",
   "    xx                            ",
   "   xx               yy            ",
   "   x              m yy            ",
   "   x           xx   yy            ",
   "   x                              ",
   "   x                              ",
   "   x                              ",
   "xxxx                          xxxx",
   "x  x                          x  x",
   "x xx    y                     xx x",
   "x                                x",
   "x @                              x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"], 
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                  ",
   "                                  ",
   "                                  ",
   "                                  ",
   "                                  ",
   "                                  ",
   "                                  ",
   "                                  ",
   "                                  ",
   "   @                              ",
   "  xxx                             ",
   "          m                       ",
   "               m                  ",
   "xxxxxxx!!!!x                      ",
   "       xxxxx!!!!x                 ",
   "  f         xxxx                  ",
   "xxxx                              ",
   "                                  ",
   "                                  ",
   "        yyy                       ",
   "        yyy                       ",
   "        yyy                       ",
   "         y                        ",
   "                                  ",
   "         y      y                 ",
   "                y         m       ",
   "                y     xxxxx       ",
   "xxxx                          xxxx",
   "x  x          x m x           x  x",
   "x xx                          xx x",
   "x                                x",
   "x                                x",
   "                                  "], 
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "              xx                   ",
   "   @            xx                 ",
   "  xxxxxxxxxx      x                ",
   "                   x               ",
   "                   x               ",
   "          x        x               ",
   " m        x        x               ",
   "          x        x               ",
   "           x       x               ",
   "           x       x               ",
   "           x       x       x       ",
   "      m    x       x       x       ",
   "           x       x       x       ",
   "           xyy     x       x       ",
   "           xyy     x       x       ",
   "           xyy     x       x       ",
   " m         xyy    x      yyx       ",
   "           vxxxxxxv      yyx       ",
   "            !!!!!!       yyx       ",
   "x                        yyx       ",
   " x                       yyx       ",
   "  xxxx                 xxxx        ",
   "      xxxxxxxxxxxxxxxxx            ",
   "                                   ",
   "                                   ",
   "                                   ",
   "                             y     ",
   "                                   ",
   "                            y      ",
   "                                   ",
   "                          y        ",
   "                                   ",
   "                                   ",
   "                                   ",
   "                                   ",
   "xxxx    x!               !x    xxxx",
   "x  x    x!!      f      !!x    x  x",
   "x xx     x!!!!       !!!!x     xx x",
   "x         xxx!!!   !!!xxx         x",
   "x            xx!!!!!xx            x",
   "               xxxxx               "],
  ["                                   ",
   "                                   ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "x                                  x",
   "x                                  x",
   "x                                  x",
   "x                                  x",
   "x                                  x",
   "x   y y  y  y y  y   y y y  y  y   x",
   "xx  y y y y y y  y   y y yy y  y  xx",
   "  x  y  y y y y  y y y y y yy    x  ",
   " x   y   y   y    y y  y y  y  y  x ",
   "x                                  x",
   "x                @                 x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"]
   
  ];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
